version: "3.9"
services:
  test:
    build:
      context: .
    container_name: "spark_test"
    environment:
      - PYTHONPATH=./src
    volumes:
      - .:/app
      - ../data:/data
    command: python3 -m pytest